version: "2.2"

services:
  server:
    image: shilazi/serverstatus:latest
    container_name: statserver
    command:
    - server
    ports:
    - "80:80"
    - "443:443"
    - "35601:35601"
    volumes:
    - ./json:/svrstat/html/json
    - ./config.json:/svrstat/hstat/config.json
    # - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
